### ISSUE TITLE
There are some error is I use /pvp <player ID>

### ISSUE THREAD

**Issue by martin1194** [aasmus/PvPToggle#20]
After I type my gameID in /pvp <player ID>
It will show those stuff
I only check the stat of mine. But I need to cool down when I using /pvp martin1194 

![image](https://user-images.githubusercontent.com/18354205/101266438-435f3d00-3792-11eb-83b6-41573bf98f8b.png)
![image](https://user-images.githubusercontent.com/18354205/101266440-478b5a80-3792-11eb-945d-f3500d5b2033.png)

**Comment by aasmus** [comment]
What version of MC is your server running?

**Comment by martin1194** [comment]
Magma-50f320e-server
forge 14.23.5.2854
MC 1.12.2

**Comment by martin1194** [comment]
I found what happen. 
The happen is I was downloaded PVP toggle 1.7.
