### ISSUE TITLE
add combatlogx

### ISSUE THREAD

**Issue by successed** [aasmus/PvPToggle#6]
add combatlogx hook please. i have combotlogx and this pvp protection.

**Comment by aasmus** [comment]
Could you give me a little bit more insight? Are you experiencing plugin conflicts or suggesting using combatlogx to calculate when to reset the cool down timer? What are the positives/negatives for this?

**Comment by successed** [comment]
I don't want the player to use this command when he's at war.

**Comment by aasmus** [comment]
Disabling PvP while in combat isn't allowed if you specify a cooldown time other than 0 in the config. Is there an issue with the current system?

**Comment by successed** [comment]
idk
